apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksplorer-role-binding
subjects:
  - kind: ServiceAccount
    name: aksplorer-sa
roleRef:
  kind: Role
  name: aksplorer-role
  apiGroup: rbac.authorization.k8s.io
