apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksplorer-deployment
spec:
  selector:
    matchLabels:
      app: aksplorer
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: aksplorer
    spec:
      serviceAccountName: aksplorer-sa
      containers:
        - name: aksplorer
          imagePullPolicy: Always
          image: ghcr.io/misha999777/aks-terraform/aksplorer:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: github-secret
