apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aksplorer-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - "aksplorer.{{ .Values.aksplorer.clusterDomain }}"
      secretName: aksplorer-certificate-secret
  rules:
    - host: "aksplorer.{{ .Values.aksplorer.clusterDomain }}"
      http:
        paths:
          - backend:
              service:
                name: aksplorer-service
                port:
                  number: 80
            path: /
            pathType: Prefix
